# Dependencies
highlighter:      pygments
markdown:         redcarpet
redcarpet:
  extensions:      ["tables"]

# Permalinks
permalink:        pretty

# Setup
title:            Castle Greyhawk
tagline:          'Castle Greyhawk Campaign'
description:      'An AD&D Campaign'
url:              http://irkinvader.github.io/castle_greyhawk
baseurl:          /castle_greyhawk
excerpt_separator: <!-- more -->

author:
  name:           'Kenin Vader'
  url:            https://irkinvader.github.io

paginate:         5

# Exclusions
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - vendor

# Custom vars
version:          2.1.2

github:
  repo:           https://github.com/irkinvader/castle_greyhawk

disqus: castlegreyhawk
