# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Castle Greyhawk
tagline:          'Castle Greyhawk Campaign'
description:      'A Campaign Notebook for the Castle Greyhawk Adventures'
url:              http://errinlarsen.github.io/castle_greyhawk/
baseurl:          /castle_greyhawk

author:
  name:           'Errin Larsen'
  url:            https://errinlarsen.github.io

paginate:         5

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/errinlarsen/castle_greyhawk

exclude: ["vendor"]
